# Generated by Django 3.2.12 on 2024-05-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_of_user',
            name='user_responses',
            field=models.JSONField(default=1612),
            preserve_default=False,
        ),
    ]
