# Generated by Django 3.2.12 on 2024-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_marks_of_user_user_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
