# Generated by Django 3.2.12 on 2024-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default='1', help_text='Duration of the quiz in minutes'),
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
